# Generated by Django 5.0.14 on 2026-10-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('correo_instructor', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('programacion', 'Programación'), ('diseno', 'Diseño'), ('idiomas', 'Idiomas'), ('marketing', 'Marketing'), ('negocios', 'Negocios'), ('otro', 'Otro')], max_length=20)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('duracion_horas', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
